server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/facehealthdatabase?useUnicode=true&character=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 9816
    #Lch18992803037
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.demo.facehealth.model
  config-location: classpath:mybatis.xml
